version: '3.9'

services:
    docker_trello_postgres:
        container_name: docker_trello_postgres
        image: postgres:latest
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - trello_network

    postgres_adminer:
        image: adminer
        restart: always
        ports:
            - "${ADMINER_PORT}:8080"
        networks:
            - trello_network

    redis_app_db:
        container_name: redis_app_db
        image: redis
        ports:
            - "6379:6379"
        restart: always

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis_app_db:6379
        ports:
            - "8081:8081"

networks:
    trello_network:
